#if !defined(__CODE_GRAV_SYSTEM_KERNEL_BLE_UUID_H__)
#define __CODE_GRAV_SYSTEM_KERNEL_BLE_UUID_H__

#define POSITION_SERVICE_UUID "c47fb085-006a-4553-a1a1-f7c40cef375e"
#define POSITION_CHARACTERISTIC_UUID "e4544465-062f-434d-b635-8c5429366fd3"

#define TEMPERATURE_SERVICE_UUID "1809"
#define TEMPERATURE_CHARACTERISTIC_UUID "2A1C"

#define BATTERY_SERVICE_UUID "180F"
#define BATTERY_LEVEL_CHARACTERISTIC_UUID "2A19"

#define DEVICE_INFO_SERVICE_UUID "180A"
#define FIRMWARE_VERSION_CHARACTERISTIC_UUID "2A26"
#define STATUS_CODE_CHARACTERISTIC_UUID "2BBB"

typedef enum {
    BLE_SERV_POSITION,
    BLE_SERV_TEMPERATURE,
    BLE_SERV_BATTERY,
    BLE_SERV_DEVICE_INFO,
    BLE_SERV_DELIM
} KernelBleServices_e;

typedef enum {
    BLE_CHT_POSITION,
    BLE_CHT_BATTERY,
    BLE_CHT_FIRMWARE,
    BLE_CHT_STATUS,
    BLE_CHT_DELIM
} KernelBleCharecteristics_e;

#endif // __CODE_GRAV_SYSTEM_KERNEL_BLE_UUID_H__
